# Generated by Django 3.2.6 on 2021-08-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.TextField(default='')),
                ('companyId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobRole', models.TextField()),
                ('jobLocation', models.TextField()),
                ('bond', models.IntegerField()),
                ('deadline', models.DateField()),
                ('package', models.IntegerField()),
                ('acceptedStudents', models.TextField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField()),
                ('liveBacklog', models.IntegerField()),
                ('deadBacklog', models.IntegerField()),
                ('passingYear', models.IntegerField()),
                ('yearGap', models.IntegerField()),
                ('skillSet', models.TextField()),
                ('offerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Criteria', to='Company.offer')),
            ],
        ),
    ]
