# Generated by Django 3.2.6 on 2021-08-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.TextField()),
                ('phoneNumber', models.TextField(default='')),
                ('dob', models.DateField(null=True)),
                ('department', models.TextField(default='')),
                ('verificationStatus', models.IntegerField(default=0)),
                ('placedOffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlacedOffer', to='Company.offer')),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(null=True)),
                ('liveBacklog', models.IntegerField(null=True)),
                ('deadBacklog', models.IntegerField(null=True)),
                ('passingYear', models.IntegerField(null=True)),
                ('yearGap', models.IntegerField(null=True)),
                ('skillSet', models.TextField(null=True)),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Eligibility', to='Student.student')),
            ],
        ),
    ]
