# Generated by Django 3.2.6 on 2021-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='skillSet',
            field=models.TextField(default=''),
        ),
    ]
